[0m[[31merror[0m] [0mFailed: : Total 4, Failed 1, Errors 0, Passed 3, Skipped 0[0m
[0m[[31merror[0m] [0mFailed tests:[0m
[0m[[31merror[0m] [0m	TestMock[0m
java.lang.RuntimeException: Tests unsuccessful
	at scala.sys.package$.error(package.scala:27)
	at scala.Predef$.error(Predef.scala:66)
	at sbt.Tests$.showResults(Tests.scala:168)
	at sbt.Defaults$$anonfun$testOnlyTask$2$$anonfun$apply$13$$anonfun$apply$15.apply(Defaults.scala:315)
	at sbt.Defaults$$anonfun$testOnlyTask$2$$anonfun$apply$13$$anonfun$apply$15.apply(Defaults.scala:314)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:41)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:41)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$5.work(System.scala:67)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:221)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:221)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:227)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:221)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:221)
	at sbt.CompletionService$$anon$1$$anon$2.call(CompletionService.scala:26)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[0m[[31merror[0m] [0m{file:/Users/k2/ProgramProjects/Scala/PlayMongo/}PlayMongo/test:[31mtest-only[0m: Tests unsuccessful[0m
